---
name: "Docker - Build image"
description: |
  Action to build and push a "raw" image with Docker for a specific platform.
  This action uses the Docker Buildx plugin to build the image.
  It supports caching.
  It returns the image digest uri, tags, and annotations, but does not handle it itself.
author: hoverkraft
branding:
  icon: package
  color: blue

outputs:
  built-image:
    description: |
      Built image data.
      Example: {
        "name": "application",
        "registry": "ghcr.io",
        "repository": "my-org/my-repo/application",
        "digest": "sha256:d31aa93410434ac9dcfc9179cac2cb1fd4d7c27f11527addc40299c7c675f49d",
        "image": "ghcr.io/my-org/my-repo/application@sha256:d31aa93410434ac9dcfc9179cac2cb1fd4d7c27f11527addc40299c7c675f49d",
        "tags": [
          "pr-63-5222075",
          "pr-63"
        ],
        "annotations": {
          "org.opencontainers.image.created": "2021-09-30T14:00:00Z",
          "org.opencontainers.image.description": "Application image"
        }
      }
    value: ${{ steps.get-built-image.outputs.built-image }}

inputs:
  oci-registry:
    description: "OCI registry where to pull and push images"
    default: "ghcr.io"
    required: true
  oci-registry-username:
    description: |
      Username used to log against the OCI registry.
      See <https://github.com/docker/login-action#usage>.
    default: ${{ github.repository_owner }}
    required: true
  oci-registry-password:
    description: |
      Password or personal access token used to log against the OCI registry.
      Can be passed in using "secrets.GITHUB_TOKEN".
      See <https://github.com/docker/login-action#usage>.
    default: ${{ github.token }}
    required: true
  repository:
    description: |
      Repository name.
      Example: 'my-org/my-repo'.
      See [Docker get-image-metadata action](../get-image-metadata/README.md).
    default: ${{ github.repository }}
    required: false
  image:
    description: |
      Additional image name.
      Example: 'application'.
      See [Docker get-image-metadata action](../get-image-metadata/README.md).
    required: false
  tag:
    description: "Force image tag to publish"
    required: false
  platform:
    description: |
      Platform to build for.
      See <https://github.com/docker/build-push-action#inputs>.
    required: true
  context:
    description: |
      Build's context is the set of files located in the specified PATH or URL.
      See <https://github.com/docker/build-push-action#inputs>.
    default: "."
    required: false
  dockerfile:
    description: |
      Location of Dockerfile (defaults to Dockerfile).
      See <https://github.com/docker/build-push-action#inputs>.
    default: "Dockerfile"
    required: false
  build-args:
    description: |
      List of build-time variables.
      See <https://github.com/docker/build-push-action#inputs>.
    required: false
  target:
    description: |
      Sets the target stage to build.
      See <https://github.com/docker/build-push-action#inputs>.
    required: false
  secrets:
    description: |
      List of secrets to expose to the build.
      See <https://docs.docker.com/build/ci/github-actions/secrets/>.
    required: false
  secret-envs:
    description: |
      List of secret environment variables to expose to the build (e.g., key=envname, MY_SECRET=MY_ENV_VAR).
      See <https://docs.docker.com/build/ci/github-actions/secrets/>.
    required: false
  cache-type:
    description: |
      Cache type.
      See <https://docs.docker.com/build/cache/backends>.
    default: "gha"
    required: false
  cache-mount-enabled:
    description: |
      Enable cache mount support using buildkit-cache-dance.
      When enabled, this will inject and extract cache mounts defined in the Dockerfile.
    type: boolean
    default: false
    required: false
  cache-mount-map:
    description: |
      Manual cache mount map in JSON format.
      Example: {"var-cache-apt": "/var/cache/apt", "var-lib-apt": "/var/lib/apt"}
      If not provided and cache-mount-enabled is true, the Dockerfile will be auto-discovered.
    required: false
    default: "{}"
  cache-mount-dir:
    description: |
      Root directory where cache content is stored.
      Only used when cache-mount-enabled is true and cache-mount-map is not provided.
    default: "cache-mount"
    required: false

runs:
  using: "composite"
  steps:
    # #region Prepare build variables

    - shell: bash
      # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
      run: mkdir -p ./self-actions/ && cp -r $GITHUB_ACTION_PATH/../../* ./self-actions/

    - id: metadata
      uses: ./self-actions/docker/get-image-metadata
      with:
        oci-registry: ${{ inputs.oci-registry }}
        repository: ${{ inputs.repository }}
        image: ${{ inputs.image }}
        tag: ${{ inputs.tag }}

    - shell: bash
      # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
      run: |
        rm -fr ./self-actions

    - id: slugify-platform
      uses: hoverkraft-tech/ci-github-common/actions/slugify@6857ef6d10f704e0998aa4955282f27d1b9be778 # 0.23.1
      with:
        value: ${{ inputs.platform }}

    - id: get-docker-config
      shell: bash
      run: |
        TAG_SUFFIX="-${{ steps.slugify-platform.outputs.result }}"

        # Add tag suffix flavor
        CACHE_FLAVOR="suffix=$TAG_SUFFIX"

        echo "cache-flavor=$CACHE_FLAVOR" >> "$GITHUB_OUTPUT"

        # Define cache image
        CACHE_TYPE="${{ inputs.cache-type }}"
        if [ "$CACHE_TYPE" = "registry" ]; then
          echo "cache-image=${{ steps.metadata.outputs.image }}/cache" >> "$GITHUB_OUTPUT"
        else
          echo "cache-image=${{ steps.metadata.outputs.image }}" >> "$GITHUB_OUTPUT"
        fi

        # Check if docker exists
        if command -v docker &> /dev/null; then
          echo "docker-exists=true" >> "$GITHUB_OUTPUT"
        fi

        PLATFORM="${{ inputs.platform }}"
        if [ -z "$PLATFORM" ]; then
          echo "platform-exists=true" >> "$GITHUB_OUTPUT"
        else
          PLATFORM_OS=$(echo "$PLATFORM" | cut -d'/' -f1)
          RUNNER_OS=$(uname -s | tr '[:upper:]' '[:lower:]')

          echo "::debug::PLATFORM_OS=$PLATFORM_OS"
          echo "::debug::RUNNER_OS=$RUNNER_OS"

          if [ "$PLATFORM_OS" = "$RUNNER_OS" ]; then
            PLATFORM_ARCH=$(echo "$PLATFORM" | cut -d'/' -f2-)
            RUNNER_ARCH=$(uname -m)

            echo "::debug::PLATFORM_ARCH=$PLATFORM_ARCH"
            echo "::debug::RUNNER_ARCH=$RUNNER_ARCH"

            # Convert runner arch to docker arch
            case $RUNNER_ARCH in
              x86_64)
                RUNNER_ARCH="amd64"
                ;;
              aarch64)
                RUNNER_ARCH="arm64"
                ;;
              armv7l)
                RUNNER_ARCH="arm/v7"
                ;;
              *)
                echo "::warning::Unsupported architecture: $RUNNER_ARCH"
                ;;
            esac

            if [ "$PLATFORM_ARCH" = "$RUNNER_ARCH" ]; then
              echo "platform-exists=true" >> "$GITHUB_OUTPUT"
            fi
          fi
        fi

    - id: cache
      uses: int128/docker-build-cache-config-action@338206c80bf9eeb2b9694b7b4fc8c247c317e2a8 # v1.38.0
      with:
        image: ${{ steps.get-docker-config.outputs.cache-image }}
        flavor: ${{ steps.get-docker-config.outputs.cache-flavor }}
        pull-request-cache: true
        cache-type: ${{ inputs.cache-type }}
        extra-cache-to: "image-manifest=true,oci-mediatypes=true"

    - id: transform-cache-gha
      if: inputs.cache-type == 'gha'
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const cacheFrom = `${{ steps.cache.outputs.cache-from }}`;
          const cacheTo = `${{ steps.cache.outputs.cache-to }}`;

          core.info(`Original cache-from: ${cacheFrom}`);
          core.info(`Original cache-to: ${cacheTo}`);

          // Transform cache-from: replace ref= with scope=
          const transformedCacheFrom = cacheFrom.replace(/ref=/g, 'scope=');

          // Transform cache-to: replace ref= with scope=
          const transformedCacheTo = cacheTo.replace(/ref=/g, 'scope=');

          core.info(`Transformed cache-from: ${transformedCacheFrom}`);
          core.info(`Transformed cache-to: ${transformedCacheTo}`);

          core.setOutput('cache-from', transformedCacheFrom);
          core.setOutput('cache-to', transformedCacheTo);

    - if: steps.get-docker-config.outputs.docker-exists != 'true'
      uses: docker/setup-docker-action@b60f85385d03ac8acfca6d9996982511d8620a19 # v4.3.0

    - if: steps.get-docker-config.outputs.platform-exists != 'true'
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      with:
        platforms: ${{ inputs.platform }}

    - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      id: setup-buildx
      with:
        # FIXME: upgrade version when available (https://github.com/docker/buildx/releases)
        version: v0.25.0
        # FIXME: upgrade version when available (https://hub.docker.com/r/moby/buildkit)
        driver-opts: |
          image=moby/buildkit:v0.23.2

    - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ${{ inputs.oci-registry }}
        username: ${{ inputs.oci-registry-username }}
        password: ${{ inputs.oci-registry-password }}

    - id: cache-mount-key
      if: inputs.cache-mount-enabled == 'true'
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          // Use the exact same cache strategy as docker-build-cache-config-action
          const cacheFrom = `${{ steps.cache.outputs.cache-from }}`;
          const imageName = `${{ inputs.image }}` || 'default';
          const platformSlug = `${{ steps.slugify-platform.outputs.result }}`;

          core.info(`Cache from: ${cacheFrom}`);

          // Extract all cache references from cache-from
          const cacheRefs = [];
          const refMatches = cacheFrom.matchAll(/ref=[^:]+:([^,\s]+)/g);
          for (const match of refMatches) {
            cacheRefs.push(match[1]);
          }

          core.info(`Extracted cache refs: ${JSON.stringify(cacheRefs)}`);

          // If no refs found, disable cache mount (shouldn't happen with int128 action)
          if (cacheRefs.length === 0) {
            core.warning('No cache refs found in cache-from output, disabling cache mount');
            core.setOutput('cache-key', '');
            core.setOutput('restore-keys', '');
            core.setOutput('cache-paths', '');
            return;
          }

          // Use first ref as primary key, others as restore keys
          const primaryRef = cacheRefs[0];
          const cacheKey = `cache-mount-${primaryRef}`;

          // Generate restore keys from additional refs
          const restoreKeys = cacheRefs.slice(1).map(ref =>
            `cache-mount-${ref}`
          );

          // Determine cache paths based on cache-mount-map
          const cacheMap = `${{ inputs.cache-mount-map }}`;
          let cachePaths;

          if (cacheMap === '{}' || cacheMap === '') {
            // Auto-discovery mode: use cache-mount-dir
            cachePaths = `${{ inputs.cache-mount-dir }}`;
          } else {
            // Manual mapping mode: extract all source paths from cache-map
            try {
              const mapObj = JSON.parse(cacheMap);
              const sourcePaths = Object.keys(mapObj);
              cachePaths = sourcePaths.join('\n');
            } catch (e) {
              core.warning(`Failed to parse cache-mount-map: ${e}. Falling back to cache-mount-dir.`);
              cachePaths = `${{ inputs.cache-mount-dir }}`;
            }
          }

          core.info(`Cache key: ${cacheKey}`);
          core.info(`Restore keys: ${JSON.stringify(restoreKeys)}`);
          core.info(`Cache paths: ${cachePaths}`);

          core.setOutput('cache-key', cacheKey);
          core.setOutput('restore-keys', restoreKeys.join('\n'));
          core.setOutput('cache-paths', cachePaths);

    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      if: inputs.cache-mount-enabled == 'true' && steps.cache-mount-key.outputs.cache-key != ''
      id: cache-mount
      with:
        path: ${{ steps.cache-mount-key.outputs.cache-paths }}
        key: ${{ steps.cache-mount-key.outputs.cache-key }}
        restore-keys: ${{ steps.cache-mount-key.outputs.restore-keys }}

    - uses: reproducible-containers/buildkit-cache-dance@5b81f4d29dc8397a7d341dba3aeecc7ec54d6361 # v3.3.0
      if: inputs.cache-mount-enabled == 'true' && steps.cache-mount-key.outputs.cache-key != ''
      with:
        builder: ${{ steps.setup-buildx.outputs.name }}
        cache-dir: ${{ inputs.cache-mount-dir }}
        dockerfile: ${{ inputs.context }}/${{ inputs.dockerfile }}
        cache-map: ${{ inputs.cache-mount-map }}
        skip-extraction: ${{ steps.cache-mount.outputs.cache-hit }}

    - id: build
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: ${{ inputs.context }}
        build-args: ${{ inputs.build-args }}
        target: ${{ inputs.target }}
        file: ${{ github.workspace }}/${{ inputs.context }}/${{ inputs.dockerfile }}
        secrets: ${{ inputs.secrets }}
        secret-envs: ${{ inputs.secret-envs }}
        platforms: ${{ inputs.platform }}
        cache-from: ${{ inputs.cache-type == 'gha' && steps.transform-cache-gha.outputs.cache-from || steps.cache.outputs.cache-from }}
        cache-to: ${{ inputs.cache-type == 'gha' && steps.transform-cache-gha.outputs.cache-to || steps.cache.outputs.cache-to }}
        outputs: "type=image,push=true,push-by-digest=true,name-canonical=true,name=${{ steps.metadata.outputs.image }}"
        labels: ${{ steps.metadata.outputs.labels }}
        annotations: ${{ steps.metadata.outputs.annotations }}

    - id: get-built-image
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const builtMetadata = ${{ steps.build.outputs.metadata }};
          if (typeof builtMetadata !== 'object') {
            core.setFailed('Given "metadata" output is not a JSON object.');
            return;
          }

          if (builtMetadata["containerimage.digest"] === undefined) {
            return core.setFailed('Given "metadata"."containerimage.digest" output is undefined.');
          }

          const name = `${{ inputs.image }}`;
          const image = `${{ steps.metadata.outputs.image }}`;
          const registryMatch = image.match(/^([^\/]+)\/.*/);
          const registry = registryMatch ? registryMatch[1] : null;
          const repositoryMatch = image.match(/^[^\/]+\/([^:]+)/);
          const repository = repositoryMatch ? repositoryMatch[1] : null;

          const tags = `${{ steps.metadata.outputs.tags }}`
          .split("\n")
          .map(tag => tag.replace(/[^\/]+\/[^:]+:(.+)/,'$1').trim())
          .filter(tag => tag !== "");

          const digests = builtMetadata["containerimage.digest"]
            .split(",")
            .map(digest => {
              const cleanedDigest = digest.trim();
              return cleanedDigest !== "" ? cleanedDigest : null;
            })
            .filter(digest => digest !== null);

          const uniqueDigests = [...new Set(digests)];
          if (uniqueDigests.length === 0) {
            return core.setFailed('No valid digests found in "containerimage.digest" output.');
          }

          if( uniqueDigests.length > 1 ) {
            return core.setFailed(`Multiple digests found: ${uniqueDigests.join(", ")}.`);
          }

          const digest = uniqueDigests[0];
          const imageWithDigest = `${image}@${digest}`;

          const annotations = `${{ steps.metadata.outputs.annotations }}`
            .split("\n")
            .map(annotation => {
              const cleanedAnnotation = annotation
                .replace(/^[^:]+:/, "")
                .trim();
              return cleanedAnnotation !== "" ? cleanedAnnotation : null;
            })
            .filter(annotation => annotation !== null)
            .reduce((annotations, annotation) => {
              const [key, value] = annotation.split("=");
              annotations[key] = value;
              return annotations;
            }, {})

          const builtImage = {
            name,
            tags,
            annotations,
            registry,
            repository,
            image: imageWithDigest,
            digest
          };

          core.setOutput("built-image", JSON.stringify(builtImage));
